description: Art Cycle Behavior

compatible: "zmk,behavior-art-cycle"

include: zero_param.yaml

properties:
    label:
        type: string
        required: false
        description: Unique label for the behavior
